package com.sumedha.commerce.auth.service;
import com.sumedha.commerce.auth.config.AuthProperties; import com.sumedha.commerce.auth.dto.request.*; import com.sumedha.commerce.auth.dto.response.*; import com.sumedha.commerce.auth.entity.*; import com.sumedha.commerce.auth.enums.UserStatus; import com.sumedha.commerce.auth.repository.*; import com.sumedha.commerce.auth.security.*; import com.sumedha.commerce.common.core.exception.*; import org.slf4j.*; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.*; import java.util.*;
@Service public class AuthServiceImpl implements AuthService { private static final Logger log=LoggerFactory.getLogger(AuthServiceImpl.class); private final UserRepository users; private final RefreshTokenRepository refreshes; private final PasswordResetTokenRepository resets; private final EmailVerificationTokenRepository verifications; private final PasswordEncoder passwords; private final JwtService jwt; private final OpaqueTokenService opaque; private final AuthProperties properties;
 public AuthServiceImpl(UserRepository u,RefreshTokenRepository r,PasswordResetTokenRepository pr,EmailVerificationTokenRepository ev,PasswordEncoder p,JwtService j,OpaqueTokenService o,AuthProperties a){users=u;refreshes=r;resets=pr;verifications=ev;passwords=p;jwt=j;opaque=o;properties=a;}
 @Transactional public AuthResponse register(RegisterRequest req){String email=normal(req.email());if(users.existsByEmail(email))throw new ConflictException("Email is already registered"); User u=users.save(new User(email,passwords.encode(req.password())));log.info("Registered auth user {}",u.getId());return issue(u);}
 @Transactional public AuthResponse login(LoginRequest req){User u=users.findByEmail(normal(req.email())).orElseThrow(this::invalidCredentials); if(!passwords.matches(req.password(),u.getPasswordHash()))throw invalidCredentials(); if(u.getStatus()!=UserStatus.ACTIVE)throw new UnauthorizedException("Account is not available");log.info("Successful login for auth user {}",u.getId());return issue(u);}
 @Transactional public AuthResponse refresh(RefreshTokenRequest req){RefreshToken old=refreshes.findByTokenHash(opaque.hash(req.refreshToken())).orElseThrow(()->new UnauthorizedException("Invalid refresh token"));if(old.isRevoked()||old.isExpired())throw new UnauthorizedException("Invalid refresh token");old.revoke();AuthResponse response=issue(old.getUser());log.info("Rotated refresh token for auth user {}",old.getUser().getId());return response;}
 @Transactional public void logout(LogoutRequest req){refreshes.findByTokenHash(opaque.hash(req.refreshToken())).ifPresent(t->{t.revoke();log.info("Revoked refresh token for auth user {}",t.getUser().getId());});}
 @Transactional public void requestPasswordReset(String email){users.findByEmail(normal(email)).ifPresent(u->{String raw=opaque.generate();resets.save(new PasswordResetToken(u,opaque.hash(raw),Instant.now().plus(Duration.ofHours(1))));log.info("Created password reset token for auth user {}",u.getId());/* future notification boundary: raw token is intentionally not delivered here */;});}
 @Transactional public void confirmPasswordReset(String token,String password){PasswordResetToken t=resets.findByTokenHash(opaque.hash(token)).orElseThrow(()->new BadRequestException("Invalid or expired reset token"));if(!t.usable())throw new BadRequestException("Invalid or expired reset token");t.getUser().changePassword(passwords.encode(password));t.use();}
 @Transactional public String createVerificationToken(UUID id){User u=users.findById(id).orElseThrow(()->new ResourceNotFoundException("User not found"));String raw=opaque.generate();verifications.save(new EmailVerificationToken(u,opaque.hash(raw),Instant.now().plus(Duration.ofHours(24))));log.info("Created email verification token for auth user {}",id);return raw;}
 @Transactional public void verifyEmail(String token){EmailVerificationToken t=verifications.findByTokenHash(opaque.hash(token)).orElseThrow(()->new BadRequestException("Invalid or expired verification token"));if(!t.usable())throw new BadRequestException("Invalid or expired verification token");t.getUser().verify();t.use();}
 private AuthResponse issue(User u){String raw=opaque.generate();refreshes.save(new RefreshToken(u,opaque.hash(raw),Instant.now().plus(properties.refreshTokenExpiration())));return new AuthResponse(u.getId(),u.getEmail(),u.getRole(),u.isVerified(),new TokenResponse(jwt.create(u),raw,"Bearer"));} private String normal(String email){return email.trim().toLowerCase(Locale.ROOT);} private UnauthorizedException invalidCredentials(){log.warn("Rejected login attempt");return new UnauthorizedException("Invalid email or password");}}
