package com.sumedha.commerce.product.controller; import com.sumedha.commerce.product.dto.request.*; import com.sumedha.commerce.product.dto.response.*; import com.sumedha.commerce.product.enums.ProductStatus; import com.sumedha.commerce.product.service.ProductService; import com.sumedha.commerce.common.core.api.ApiResponse; import com.sumedha.commerce.common.core.constants.ApiConstants; import com.sumedha.commerce.common.core.enums.SortDirection; import com.sumedha.commerce.common.core.pagination.PageRequest; import com.sumedha.commerce.common.core.pagination.PageResponse; import jakarta.validation.Valid; import org.springframework.http.*; import org.springframework.web.bind.annotation.*; import java.math.BigDecimal; import java.util.*;
@RestController @RequestMapping("/api/v1/products") public class ProductController {private final ProductService service;public ProductController(ProductService service){this.service=service;}
@PostMapping public ResponseEntity<ApiResponse<ProductResponse>> create(@Valid @RequestBody CreateProductRequest r){return ResponseEntity.status(HttpStatus.CREATED).body(ApiResponse.success(service.create(r)));}
@GetMapping("/{productId}") public ApiResponse<ProductResponse> get(@PathVariable("productId") UUID productId){return ApiResponse.success(service.get(productId));}
@GetMapping("/slug/{slug}") public ApiResponse<ProductResponse> getBySlug(@PathVariable("slug") String slug){return ApiResponse.success(service.getBySlug(slug));}
@PutMapping("/{productId}") public ApiResponse<ProductResponse> update(@PathVariable("productId") UUID productId,@Valid @RequestBody UpdateProductRequest r){return ApiResponse.success(service.update(productId,r));}
@DeleteMapping("/{productId}") public ResponseEntity<Void> delete(@PathVariable("productId") UUID productId){service.delete(productId);return ResponseEntity.noContent().build();}
@GetMapping public ApiResponse<PageResponse<ProductSummaryResponse>> search(@RequestParam(name="search",required=false) String search,@RequestParam(name="categoryId",required=false) UUID categoryId,@RequestParam(name="brandId",required=false) UUID brandId,@RequestParam(name="status",required=false) ProductStatus status,@RequestParam(name="minPrice",required=false) BigDecimal minPrice,@RequestParam(name="maxPrice",required=false) BigDecimal maxPrice,@RequestParam(name="page",defaultValue=""+ApiConstants.DEFAULT_PAGE_NUMBER) int page,@RequestParam(name="size",defaultValue=""+ApiConstants.DEFAULT_PAGE_SIZE) int size,@RequestParam(name="sortBy",defaultValue="createdAt") String sortBy,@RequestParam(name="sortDirection",defaultValue="ASC") SortDirection sortDirection){ProductFilter filter=new ProductFilter(search,categoryId,brandId,status,minPrice,maxPrice);PageRequest pageRequest=PageRequest.of(page,size,sortDirection,sortBy);return ApiResponse.success(service.search(filter,pageRequest));}
}
