import { FormEvent, useState } from 'react';
import { ApiError } from '../api/client';
import { userApi } from '../api/services';
import { useAuth } from '../features/auth/AuthContext';
import { useAsync } from '../hooks/useAsync';
import { ErrorState, Loader } from '../components/Feedback';

export function AccountPage() {
  const { user } = useAuth(); const profile = useAsync(async () => { try { return await userApi.profile(user!.userId); } catch (error) { if (error instanceof ApiError && error.status === 404) return null; throw error; } }, [user!.userId]); const addresses = useAsync(() => userApi.addresses(user!.userId), [user!.userId]); const preferences = useAsync(async () => { try { return await userApi.preferences(user!.userId); } catch (error) { if (error instanceof ApiError && error.status === 404) return null; throw error; } }, [user!.userId]); const [notice, setNotice] = useState('');
  if (profile.loading) return <Loader label="Loading account" />; if (profile.error) return <ErrorState message={profile.error} retry={() => void profile.reload()} />;
  const saveProfile = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const value = { firstName: String(form.get('firstName')), lastName: String(form.get('lastName')), phone: String(form.get('phone')) || null, avatarUrl: String(form.get('avatarUrl')) || null, dateOfBirth: String(form.get('dateOfBirth')) || null }; if (profile.data) await userApi.updateProfile(user!.userId, value); else await userApi.createProfile(user!.userId, value); setNotice('Profile saved.'); await profile.reload(); };
  const savePrefs = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); await userApi.updatePreferences(user!.userId, { language: String(form.get('language')) || null, currency: String(form.get('currency')) || null, marketingEmails: form.get('marketingEmails') === 'on', orderNotifications: form.get('orderNotifications') === 'on' }); setNotice('Preferences saved.'); await preferences.reload(); };
  return <section className="page-section narrow"><div className="page-title"><p className="eyebrow">Account</p><h1>Your profile</h1><p>{user!.email} · {user!.role}</p></div>{notice && <p className="success-note" role="status">{notice}</p>}<div className="account-grid"><form className="panel stack" onSubmit={e => void saveProfile(e)}><h2>Personal details</h2><div className="field-pair"><label>First name<input name="firstName" required maxLength={100} defaultValue={profile.data?.firstName} /></label><label>Last name<input name="lastName" required maxLength={100} defaultValue={profile.data?.lastName} /></label></div><label>Phone<input name="phone" maxLength={40} defaultValue={profile.data?.phone || ''} /></label><label>Avatar URL<input name="avatarUrl" type="url" maxLength={2048} defaultValue={profile.data?.avatarUrl || ''} /></label><label>Date of birth<input name="dateOfBirth" type="date" max={new Date().toISOString().slice(0, 10)} defaultValue={profile.data?.dateOfBirth || ''} /></label><button className="button">Save profile</button></form><form className="panel stack" onSubmit={e => void savePrefs(e)}><h2>Preferences</h2><label>Language<input name="language" minLength={2} maxLength={10} defaultValue={preferences.data?.language || ''} placeholder="en" /></label><label>Currency<input name="currency" minLength={3} maxLength={3} defaultValue={preferences.data?.currency || ''} placeholder="USD" /></label><label className="check"><input name="marketingEmails" type="checkbox" defaultChecked={preferences.data?.marketingEmails} /> Marketing emails</label><label className="check"><input name="orderNotifications" type="checkbox" defaultChecked={preferences.data?.orderNotifications} /> Order notifications</label><button className="button">Save preferences</button></form></div><section className="address-section"><h2>Saved addresses</h2>{addresses.loading ? <Loader /> : addresses.error ? <p className="form-error">{addresses.error}</p> : !addresses.data?.length ? <p className="muted">No saved addresses.</p> : <div className="address-grid">{addresses.data.map(address => <address key={address.addressId}><strong>{address.type}{address.isDefault ? ' · Default' : ''}</strong><span>{address.recipientName}</span><span>{address.line1}{address.line2 ? `, ${address.line2}` : ''}</span><span>{address.postalCode} {address.city}</span><span>{address.countryCode}</span></address>)}</div>}<p className="muted small">Address viewing is available here. Address editing is a known UI limitation.</p></section></section>;
}
