import { FormEvent, useState } from 'react';
import { Link, NavLink, Outlet, useParams } from 'react-router-dom';
import { adminApi, productApi } from '../api/services';
import { useAsync } from '../hooks/useAsync';
import { EmptyState, ErrorState, Loader, Status } from '../components/Feedback';
import { date, money } from '../utils/format';
import type { Product, ProductWrite } from '../types';

export function AdminLayout() { return <section className="admin-shell"><aside><p className="eyebrow light">Operations</p><h1>Admin</h1><nav><NavLink to="/admin/products">Products</NavLink><NavLink to="/admin/dlt">Dead letters</NavLink></nav></aside><div className="admin-content"><Outlet /></div></section>; }
export function AdminProductsPage() { const products = useAsync(() => productApi.list(0, 100, ''), []); const categories = useAsync(() => productApi.categories(), []); const brands = useAsync(() => productApi.brands(), []); const [editing, setEditing] = useState<Product | null>(null); const [error, setError] = useState('');
  const save = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setError(''); const form = new FormData(event.currentTarget); const value: ProductWrite = { ...(editing ? {} : { sku: String(form.get('sku')) }), name: String(form.get('name')), slug: String(form.get('slug')), categoryId: String(form.get('categoryId')), brandId: String(form.get('brandId')) || null, price: Number(form.get('price')), currency: String(form.get('currency')), ...(editing ? { shortDescription: editing.shortDescription, description: editing.description, status: String(form.get('status')) as ProductWrite['status'], active: form.get('active') === 'on' } : {}) }; try { if (editing) await productApi.update(editing.productId, value); else await productApi.create(value); setEditing(null); event.currentTarget.reset(); await products.reload(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to save product'); } };
  if (products.loading || categories.loading || brands.loading) return <Loader label="Loading product administration" />; if (products.error) return <ErrorState message={products.error} />; return <><div className="admin-heading"><div><p className="eyebrow">Catalogue administration</p><h2>Products</h2></div></div>{error && <p className="form-error" role="alert">{error}</p>}<form key={editing?.productId || 'new'} className="admin-form" onSubmit={e => void save(e)}><h3>{editing ? 'Edit product' : 'Create product'}</h3>{!editing && <label>SKU<input name="sku" required maxLength={100} /></label>}<label>Name<input name="name" required maxLength={200} defaultValue={editing?.name} /></label><label>Slug<input name="slug" required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" defaultValue={editing?.slug} /></label><label>Category<select name="categoryId" required defaultValue={editing?.category.categoryId}>{categories.data?.map(c => <option key={c.categoryId} value={c.categoryId}>{c.name}</option>)}</select></label><label>Brand<select name="brandId" defaultValue={editing?.brand?.brandId || ''}><option value="">No brand</option>{brands.data?.map(b => <option key={b.brandId} value={b.brandId}>{b.name}</option>)}</select></label><label>Price<input name="price" type="number" required min="0" step="0.01" defaultValue={editing?.price} /></label><label>Currency<input name="currency" required pattern="[A-Za-z]{3}" defaultValue={editing?.currency || 'USD'} /></label>{editing && <><label>Status<select name="status" defaultValue={editing.status}><option>ACTIVE</option><option>DRAFT</option><option>INACTIVE</option><option>DISCONTINUED</option></select></label><label className="check"><input name="active" type="checkbox" defaultChecked={editing.active} /> Active</label></>}<div className="form-actions"><button className="button">{editing ? 'Update' : 'Create'}</button>{editing && <button type="button" className="button secondary" onClick={() => setEditing(null)}>Cancel</button>}</div></form>{!products.data?.items.length ? <EmptyState title="No products" text="Create the first catalogue product." /> : <div className="table-wrap"><table><thead><tr><th>Name</th><th>SKU</th><th>Price</th><th>Actions</th></tr></thead><tbody>{products.data.items.map(p => <tr key={p.productId}><td><Link to={`/products/${p.productId}`}>{p.name}</Link></td><td>{p.sku}</td><td>{money(p.price, p.currency)}</td><td><button className="text-button" onClick={async () => { setError(''); try { setEditing(await productApi.get(p.productId)); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to load product'); } }}>Edit</button><button className="text-button danger" onClick={async () => { if (confirm(`Delete ${p.name}? This cannot be undone.`)) { await productApi.remove(p.productId); await products.reload(); } }}>Delete</button></td></tr>)}</tbody></table></div>}</>; }
export function AdminDltPage() { const records = useAsync(() => adminApi.dlt(), []); if (records.loading) return <Loader label="Loading dead letters" />; if (records.error) return <ErrorState message={records.error} retry={() => void records.reload()} />; return <><div className="admin-heading"><div><p className="eyebrow">Payment event operations</p><h2>Dead letters</h2></div></div>{!records.data?.items.length ? <EmptyState title="No dead letters" text="The payment event dead-letter store is clear." /> : <div className="table-wrap"><table><thead><tr><th>Event</th><th>First seen</th><th>Status</th><th>Replays</th></tr></thead><tbody>{records.data.items.map(item => <tr key={item.id}><td><Link to={`/admin/dlt/${item.id}`}>{item.eventType || 'Unparsed event'}</Link><small>{item.eventId || item.id}</small></td><td>{date(item.firstSeenAt)}</td><td><Status value={item.status} /></td><td>{item.replayCount}</td></tr>)}</tbody></table></div>}</>; }
export function AdminDltDetailPage() { const { id = '' } = useParams(); const record = useAsync(() => adminApi.dltDetail(id), [id]); const [notice, setNotice] = useState(''); if (record.loading) return <Loader />; if (record.error || !record.data) return <ErrorState message={record.error || 'Record not found'} />; const item = record.data.event; return <><Link className="text-link" to="/admin/dlt">← Dead letters</Link><div className="admin-heading"><div><p className="eyebrow">DLT record</p><h2>{item.eventType || 'Unparsed event'}</h2></div><Status value={item.status} /></div>{notice && <p className="success-note">{notice}</p>}<dl className="detail-list"><div><dt>Record ID</dt><dd>{item.id}</dd></div><div><dt>Original topic</dt><dd>{item.originalTopic}</dd></div><div><dt>Exception</dt><dd>{item.exceptionClass}: {item.exceptionMessage}</dd></div></dl><h3>Original payload</h3><pre className="payload">{record.data.payload}</pre><button className="button danger-button" onClick={async () => { if (confirm('Replay this stored event to its original topic?')) { await adminApi.replay(id); setNotice('Replay acknowledged.'); await record.reload(); } }}>Replay stored event</button></>; }
