import { FormEvent, useState } from 'react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { useAuth } from '../features/auth/AuthContext';

function AuthForm({ register = false }: { register?: boolean }) {
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const auth = useAuth(); const navigate = useNavigate(); const location = useLocation();
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(''); try { if (register) await auth.register(email, password); else await auth.login(email, password); navigate((location.state as { from?: string } | null)?.from || '/'); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Authentication failed'); } finally { setBusy(false); } };
  return <div className="auth-page"><section className="auth-panel"><Link className="brand" to="/"><span className="brand-mark">N</span><span>Northstar</span></Link><p className="eyebrow">{register ? 'Join Northstar' : 'Welcome back'}</p><h1>{register ? 'Create your account' : 'Sign in to continue'}</h1><p className="muted">{register ? 'Save your cart, check out, and follow your orders.' : 'Access your cart, orders, and account.'}</p>{error && <p className="form-error" role="alert">{error}</p>}<form onSubmit={submit} className="stack"><label>Email<input type="email" autoComplete="email" required maxLength={320} value={email} onChange={e => setEmail(e.target.value)} /></label><label>Password<input type="password" autoComplete={register ? 'new-password' : 'current-password'} required minLength={register ? 12 : undefined} maxLength={128} value={password} onChange={e => setPassword(e.target.value)} /></label>{register && <small>Password must be 12–128 characters and contain a letter and a number.</small>}<button className="button" disabled={busy}>{busy ? 'Please wait…' : register ? 'Create account' : 'Sign in'}</button></form><p>{register ? 'Already registered?' : 'New here?'} <Link className="text-link" to={register ? '/login' : '/register'}>{register ? 'Sign in' : 'Create an account'}</Link></p></section><aside className="auth-aside"><p className="eyebrow light">Distributed commerce, one clear experience</p><blockquote>Explore the real catalogue, manage a service-backed cart, and check out through the platform gateway.</blockquote></aside></div>;
}
export const LoginPage = () => <AuthForm />;
export const RegisterPage = () => <AuthForm register />;
