import { Link, useParams } from 'react-router-dom';
import { orderApi } from '../api/services';
import { useAuth } from '../features/auth/AuthContext';
import { useAsync } from '../hooks/useAsync';
import { EmptyState, ErrorState, Loader, Status } from '../components/Feedback';
import { date, money } from '../utils/format';

export function OrdersPage() { const { user } = useAuth(); const result = useAsync(() => orderApi.forUser(user!.userId), [user!.userId]); if (result.loading) return <Loader label="Loading orders" />; if (result.error) return <ErrorState message={result.error} retry={() => void result.reload()} />; return <section className="page-section narrow"><div className="page-title"><p className="eyebrow">Account</p><h1>Your orders</h1></div>{!result.data?.length ? <EmptyState title="No orders yet" text="Completed checkouts will appear here." /> : <div className="order-list">{result.data.map(order => <Link className="order-row" to={`/orders/${order.id}`} key={order.id}><div><strong>Order {order.id.slice(0, 8)}</strong><span>{date(order.createdAt)}</span></div><Status value={order.status} /><strong>{money(order.total, order.currency)}</strong></Link>)}</div>}</section>; }
export function OrderPage() { const { id = '' } = useParams(); const result = useAsync(() => orderApi.get(id), [id]); if (result.loading) return <Loader label="Loading order" />; if (result.error || !result.data) return <ErrorState message={result.error || 'Order not found'} retry={() => void result.reload()} />; const order = result.data; return <section className="page-section narrow"><Link className="text-link" to="/orders">← All orders</Link><div className="page-title"><p className="eyebrow">Order {order.id}</p><h1>Order details</h1><Status value={order.status} /></div><div className="order-items">{order.items.map(item => <div key={item.id}><div><strong>{item.productName}</strong><span>{item.sku || 'No SKU'} · Qty {item.quantity}</span></div><strong>{money(item.lineTotal, order.currency)}</strong></div>)}</div><div className="order-total"><span>Total</span><strong>{money(order.total, order.currency)}</strong></div></section>; }
