import { FormEvent } from 'react';
import { useSearchParams } from 'react-router-dom';
import { searchApi } from '../api/services';
import { useAsync } from '../hooks/useAsync';
import { EmptyState, ErrorState } from '../components/Feedback';
import { ProductCard } from '../components/ProductCard';
import { Pagination } from './CataloguePage';

export function SearchPage() {
  const [params, setParams] = useSearchParams(); const values = Object.fromEntries(params); const page = Number(values.page) || 0;
  const result = useAsync(() => searchApi.search({ q: values.q, minPrice: values.minPrice, maxPrice: values.maxPrice, currency: values.currency, sort: values.sort || 'relevance', status: 'ACTIVE', page, size: 12 }), [params.toString()]);
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const next = new URLSearchParams(); ['q','minPrice','maxPrice','currency','sort'].forEach(key => { const value = String(form.get(key) || '').trim(); if (value && !(key === 'sort' && value === 'relevance')) next.set(key, value); }); setParams(next); };
  return <section className="page-section"><div className="page-title"><p className="eyebrow">Search service</p><h1>Find your next essential</h1></div><form className="filter-bar" onSubmit={submit}><label>Search<input name="q" defaultValue={values.q} maxLength={200} placeholder="Name, SKU, or description" /></label><label>Min price<input name="minPrice" type="number" min="0" step="0.01" defaultValue={values.minPrice} /></label><label>Max price<input name="maxPrice" type="number" min="0" step="0.01" defaultValue={values.maxPrice} /></label><label>Currency<input name="currency" maxLength={3} defaultValue={values.currency} placeholder="USD" /></label><label>Sort<select name="sort" defaultValue={values.sort || 'relevance'}><option value="relevance">Relevance</option><option value="priceAsc">Price: low to high</option><option value="priceDesc">Price: high to low</option><option value="nameAsc">Name: A–Z</option><option value="nameDesc">Name: Z–A</option></select></label><button className="button">Search</button></form>{result.loading ? <div className="product-grid skeleton-grid">{Array.from({length: 8}, (_, i) => <div className="skeleton" key={i} />)}</div> : result.error ? <ErrorState message={result.error} retry={() => void result.reload()} /> : !result.data?.items.length ? <EmptyState title="No matches" text="Try a broader phrase or adjust the supported filters." /> : <><div className="results-meta">{result.data.totalElements} results</div><div className="product-grid">{result.data.items.map(product => <ProductCard key={product.productId} product={product} />)}</div><Pagination page={page} hasNext={result.data.hasNext} hasPrevious={result.data.hasPrevious} onChange={next => { const p = new URLSearchParams(params); if (next) p.set('page', String(next)); else p.delete('page'); setParams(p); }} /></>}</section>;
}
