package com.sumedha.commerce.product.service; import com.sumedha.commerce.product.dto.request.*; import com.sumedha.commerce.product.dto.response.*; import com.sumedha.commerce.product.entity.Category; import com.sumedha.commerce.product.mapper.CategoryMapper; import com.sumedha.commerce.product.repository.CategoryRepository; import com.sumedha.commerce.product.repository.ProductRepository; import com.sumedha.commerce.common.core.exception.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.*;
@Service public class CategoryServiceImpl implements CategoryService {private final CategoryRepository categories;private final ProductRepository products;public CategoryServiceImpl(CategoryRepository c,ProductRepository p){categories=c;products=p;}
@Transactional public CategoryResponse create(CreateCategoryRequest r){if(categories.existsBySlug(r.slug()))throw new ConflictException("Category slug already exists");if(r.parentCategoryId()!=null&&!categories.existsById(r.parentCategoryId()))throw new ResourceNotFoundException("Parent category not found");Category c=categories.save(new Category(r.name(),r.slug(),r.description(),r.parentCategoryId()));return CategoryMapper.toResponse(c);}
@Transactional(readOnly=true) public List<CategoryResponse> list(){return categories.findAll().stream().map(CategoryMapper::toResponse).toList();}
@Transactional(readOnly=true) public CategoryResponse get(UUID categoryId){return CategoryMapper.toResponse(category(categoryId));}
@Transactional public CategoryResponse update(UUID categoryId,UpdateCategoryRequest r){Category c=category(categoryId);if(r.parentCategoryId()!=null){if(r.parentCategoryId().equals(categoryId))throw new BadRequestException("Category cannot be its own parent");if(!categories.existsById(r.parentCategoryId()))throw new ResourceNotFoundException("Parent category not found");}if(categories.existsBySlugAndIdNot(r.slug(),categoryId))throw new ConflictException("Category slug already exists");c.update(r.name(),r.slug(),r.description(),r.parentCategoryId(),r.active());return CategoryMapper.toResponse(c);}
@Transactional public void delete(UUID categoryId){Category c=category(categoryId);if(categories.existsByParentCategoryId(categoryId))throw new ConflictException("Category has child categories");if(products.existsByCategoryId(categoryId))throw new ConflictException("Category has products");categories.delete(c);}
private Category category(UUID id){return categories.findById(id).orElseThrow(()->new ResourceNotFoundException("Category not found"));}
}
