package com.sumedha.commerce.product.service; import com.sumedha.commerce.product.dto.request.*; import com.sumedha.commerce.product.dto.response.*; import com.sumedha.commerce.product.entity.Product; import com.sumedha.commerce.product.entity.ProductImage; import com.sumedha.commerce.product.mapper.ProductMapper; import com.sumedha.commerce.product.repository.ProductImageRepository; import com.sumedha.commerce.product.repository.ProductRepository; import com.sumedha.commerce.common.core.exception.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.*;
@Service public class ProductImageServiceImpl implements ProductImageService {private final ProductRepository products;private final ProductImageRepository images;public ProductImageServiceImpl(ProductRepository p,ProductImageRepository i){products=p;images=i;}
@Transactional public ProductImageResponse create(UUID productId,CreateProductImageRequest r){product(productId);if(r.primaryImage())clearPrimary(productId,null);ProductImage img=images.save(new ProductImage(productId,r.url(),r.altText(),r.sortOrder(),r.primaryImage()));return ProductMapper.toImageResponse(img);}
@Transactional(readOnly=true) public List<ProductImageResponse> list(UUID productId){product(productId);return images.findByProductIdOrderBySortOrderAsc(productId).stream().map(ProductMapper::toImageResponse).toList();}
@Transactional public ProductImageResponse update(UUID productId,UUID imageId,UpdateProductImageRequest r){product(productId);ProductImage img=image(productId,imageId);if(r.primaryImage())clearPrimary(productId,imageId);img.update(r.url(),r.altText(),r.sortOrder(),r.primaryImage());return ProductMapper.toImageResponse(img);}
@Transactional public void delete(UUID productId,UUID imageId){product(productId);ProductImage img=image(productId,imageId);images.delete(img);}
private void clearPrimary(UUID productId,UUID exceptImageId){images.findByProductIdAndPrimaryImageTrue(productId).filter(p->!p.getId().equals(exceptImageId)).ifPresent(p->p.setPrimaryImage(false));}
private Product product(UUID id){return products.findById(id).orElseThrow(()->new ResourceNotFoundException("Product not found"));}
private ProductImage image(UUID productId,UUID imageId){return images.findByIdAndProductId(imageId,productId).orElseThrow(()->new ResourceNotFoundException("Product image not found"));}
}
