package com.sumedha.commerce.product.service; import com.sumedha.commerce.product.dto.request.*; import com.sumedha.commerce.product.dto.response.*; import com.sumedha.commerce.product.entity.Brand; import com.sumedha.commerce.product.entity.Category; import com.sumedha.commerce.product.entity.Product; import com.sumedha.commerce.product.mapper.BrandMapper; import com.sumedha.commerce.product.mapper.CategoryMapper; import com.sumedha.commerce.product.mapper.ProductMapper; import com.sumedha.commerce.product.repository.BrandRepository; import com.sumedha.commerce.product.repository.CategoryRepository; import com.sumedha.commerce.product.repository.ProductAttributeRepository; import com.sumedha.commerce.product.repository.ProductImageRepository; import com.sumedha.commerce.product.repository.ProductRepository; import com.sumedha.commerce.product.repository.ProductSpecifications; import com.sumedha.commerce.common.core.exception.*; import com.sumedha.commerce.common.core.pagination.PageRequest; import com.sumedha.commerce.common.core.pagination.PageResponse; import org.springframework.data.domain.Page; import org.springframework.data.domain.Sort; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.*;
@Service public class ProductServiceImpl implements ProductService {private static final Set<String> ALLOWED_SORT_FIELDS=Set.of("name","price","createdAt","updatedAt");private final ProductRepository products;private final CategoryRepository categories;private final BrandRepository brands;private final ProductImageRepository images;private final ProductAttributeRepository attributes;public ProductServiceImpl(ProductRepository p,CategoryRepository c,BrandRepository b,ProductImageRepository i,ProductAttributeRepository a){products=p;categories=c;brands=b;images=i;attributes=a;}
@Transactional public ProductResponse create(CreateProductRequest r){if(products.existsBySku(r.sku()))throw new ConflictException("Product SKU already exists");if(products.existsBySlug(r.slug()))throw new ConflictException("Product slug already exists");Category c=categories.findById(r.categoryId()).orElseThrow(()->new ResourceNotFoundException("Category not found"));Brand b=r.brandId()==null?null:brands.findById(r.brandId()).orElseThrow(()->new ResourceNotFoundException("Brand not found"));Product p=products.save(new Product(r.sku(),r.name(),r.slug(),r.categoryId(),r.brandId(),r.price(),r.currency()));return toResponse(p,c,b);}
@Transactional(readOnly=true) public ProductResponse get(UUID productId){return toResponse(product(productId));}
@Transactional(readOnly=true) public ProductResponse getBySlug(String slug){return toResponse(products.findBySlug(slug).orElseThrow(()->new ResourceNotFoundException("Product not found")));}
@Transactional public ProductResponse update(UUID productId,UpdateProductRequest r){Product p=product(productId);if(products.existsBySlugAndIdNot(r.slug(),productId))throw new ConflictException("Product slug already exists");Category c=categories.findById(r.categoryId()).orElseThrow(()->new ResourceNotFoundException("Category not found"));Brand b=r.brandId()==null?null:brands.findById(r.brandId()).orElseThrow(()->new ResourceNotFoundException("Brand not found"));p.update(r.name(),r.slug(),r.shortDescription(),r.description(),r.categoryId(),r.brandId(),r.price(),r.currency(),r.status(),r.active());return toResponse(p,c,b);}
@Transactional public void delete(UUID productId){Product p=product(productId);if(images.existsByProductId(productId))throw new ConflictException("Product has images");if(attributes.existsByProductId(productId))throw new ConflictException("Product has attributes");products.delete(p);}
@Transactional(readOnly=true) public PageResponse<ProductSummaryResponse> search(ProductFilter filter,PageRequest pageRequest){if(filter.minPrice()!=null&&filter.maxPrice()!=null&&filter.minPrice().compareTo(filter.maxPrice())>0)throw new BadRequestException("minPrice must not be greater than maxPrice");if(!ALLOWED_SORT_FIELDS.contains(pageRequest.getSortBy()))throw new BadRequestException("Invalid sort field: "+pageRequest.getSortBy());Sort sort=Sort.by(Sort.Direction.valueOf(pageRequest.getSortDirection().name()),pageRequest.getSortBy());org.springframework.data.domain.PageRequest springPage=org.springframework.data.domain.PageRequest.of(pageRequest.getPage(),pageRequest.getSize(),sort);Page<Product> result=products.findAll(ProductSpecifications.filterBy(filter),springPage);List<ProductSummaryResponse> items=result.getContent().stream().map(ProductMapper::toSummary).toList();return PageResponse.of(items,pageRequest.getPage(),pageRequest.getSize(),result.getTotalElements());}
private Product product(UUID id){return products.findById(id).orElseThrow(()->new ResourceNotFoundException("Product not found"));}
private ProductResponse toResponse(Product p){Category c=categories.findById(p.getCategoryId()).orElseThrow(()->new ResourceNotFoundException("Category not found"));Brand b=p.getBrandId()==null?null:brands.findById(p.getBrandId()).orElseThrow(()->new ResourceNotFoundException("Brand not found"));return toResponse(p,c,b);}
private ProductResponse toResponse(Product p,Category c,Brand b){List<ProductImageResponse> i=images.findByProductIdOrderBySortOrderAsc(p.getId()).stream().map(ProductMapper::toImageResponse).toList();List<ProductAttributeResponse> a=attributes.findByProductId(p.getId()).stream().map(ProductMapper::toAttributeResponse).toList();return ProductMapper.toResponse(p,CategoryMapper.toResponse(c),b==null?null:BrandMapper.toResponse(b),i,a);}
}
